<<<<<<< HEAD
name: The SILShack class blog - Fall 2013
pygments: true
markdown: redcarpet

baseurl: /fall2013
url: 

course:
  title: Programming for Information Professionals
  number: INLS 560
  instructor: Elliott Hauser
=======
name: SILShack Spring 2014
pygments: true
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough"]

timezone: America/New_York

special-categories: 
  - "exercise"
  - "how-to"

# These can contain uppercase: they'll be lowercased in the URL
page-order:
  - syllabus
  - schedule
  - exercises
  - how-to
  - people
  - feedback
  - music

# Same note RE case above
python-extra-pages:
  - console
  
>>>>>>> b77e81d49f0bf0f945b5025ace5a79ac787b13b9
  
baseurl: /spring2014
url: /spring2014

python: true

course:
  title: Programming for Information Professionals
  number: INLS 560
  instructor: Prof. Elliott Hauser
  semester: Spring 2014

authors:
  elliott:
      name: Elliott Hauser
<<<<<<< HEAD
      prof: true
      gravatar: 0d0d432948d262195358f339768f1240
      website: http://www.elliotthauser.com
      github: eah13
      twitter: hauspoor
      about:  Elliott Hauser is a PhD Student in information science at UNC Chapel Hill.  He's hacking education as one of the cofounders of Coursefork.org.  
  mbaxter:
      name: Michelle Baxter
      prof: false
      gravatar: a3e29e2e2b46aa5e21cf3e56fccdf2b0
      website: http://www.facebook.com/mbbaxter
      github: EmBeeBee
      twitter: MichelleBBaxter
      about:  Grad student, pop culture enthusiast.
  abrown:
      name: Ashley Brown
      prof: false
      gravatar:
      website: 
      github: ashmbrown
      twitter: 
      about: I am a dual Master's student studying Library Science and Public Administration.  
  sburnham:
      name: Sarah Breen
      prof: false
      gravatar:
      website: 
      github: sbbreen
      twitter:
      about: Sarah is a first year MSIS student. Originally from Ohio, she has spent the last five years in Asia working in archives and as a project manager for several small organizations. Reach her on email at sburnham5@gmail.com. 
  ecarter:
      name: Erin Carter
      prof: false
      gravatar:
      website: http://erinlcarter.com
      github: erincarter
      about: Erin is a second-year MSIS student. She works at the SILS Help Desk, stop on by!  
  odorsey:
      name: Olivia Dorsey
      prof: false
      gravatar:
      website: http://franklinmemories.com
      github: odorsey
      twitter:
      about: Olivia is a senior BSIS student who is interested in web design/development and the digital humanities. Her hometown is Clayton, NC.

  jgeer:
      name: James Geer
      prof: false
      gravatar:
      website: 
      github: jkgeer
      twitter: JakeGeer
      about: James Geer is a MSIS student at UNC-Chapel Hill after graduating from UNC's undergrad with a degree in Strategic Communications.
  mgillen:
      name: Mary Gillen
      prof: false
      gravatar:
      website: 
      github: gillenme
      twitter:
      about:  Mary is a second year MSIS student focusing on information retrieval. Her interests include big data, data analytics and marketing.
  lgrindheim:
      name: Landon Grindheim
      prof: false
      gravatar:
      website: 
      github: landongrindheim
      twitter: landongrindheim
      about: Landon is, man.
  alexharding:
      name: Alexander Harding
      prof: false
      gravatar:
      website: 
      github: JaguarPhD
      twitter:
      about: Alex is a second year MSIS student at SILS and the bottom of the totem pole in the UNC Libraries IT Systems department. He looks forward to working with everyone in this class! 
  lho:
      name: Leslie Ho
      prof: false
      gravatar:
      website: 
      github: leslieho
      twitter:
      about: Leslie is a BSIS and Anthropology double major.  She really likes puppies.
  erholmes:
      name: Erin Holmes
      prof: false
      gravatar:
      website: http://www.linkedin.com/in/holmeserin
      github: erholmes
      twitter: erinh24
      about:  Erin is a second year MSIS student and is trying her best at life! She hopes to be a git rockstar in about 3 months!
  ckenrick:
      name: Christopher Kenrick
      prof: false
      gravatar: 03d788ea2c609688892fa66b8c5886ed
      website: 
      github: IAMATinyCoder
      twitter: ChrisKenrick
      about: Christopher is a dual-degree student studying Information Science and Public Administration.  
  smantooth:
      name: Stacey Mantooth
      prof: false
      gravatar: d3277996b61f2805d4b971b62961bd4a
      website: 
      github: allhailaugustus
      twitter: allhailaugustus
      about: |
        Llamas graze steep slopes,
        all lulled, sun-warmed and drowsy,
        wind ruffling coats.
        
        Stacey likes short poems and Peruvian quadrupeds.
  gmclendon:
      name: Grant McLendon
      prof: false
      gravatar: eeb73c80c4450528bf5eac5f1dedae9e
      website: http://gerbal.org
      github: gerbal
      twitter: gerbal100
      about:  Grant's a first year MSIS student.  
  carolinp: 
      name: Caroline Pate
      prof: false
      gravatar:
      website: http://www.carolinepate.com/portfolio
      github: carolinp
      twitter: ugh_caroline
      about: Caroline is a senior multimedia journalism major at UNC Chapel Hill. Her interests include music, television, cats, pizza, and beautiful news applications that tell a story.
  dpcolar:
      name: David Pcolar
      prof: false
      gravatar:
      website: http://library.unc.edu
      github: pcolar
      twitter: pcolar
      about:  Dave is an IT professional with the University Library. My focus is infrastructure related project management and research on scalable storage environments. 
  epeele:
      name: Elizabeth Peele
      prof: false
      gravatar: 0ccbe343ca162877a845c41be907fea5
      website: 
      github: eipeele
      twitter: eipeele
      about:  Elizabeth Peele is a first year MSIS at the University of North Carolina Chapel Hill.  
  jpowell:
      name: Jaleesa Powell
      prof: false
      gravatar: 189c604692e488809bcf2770b70cc491
      website: http://jaleesapowell.net
      github: dieschwarzekobra
      twitter: JaleesaPowell
      about: Jaleesa is a second-year MSIS student at the University of North Carolina at Chapel Hill. Jaleesa is a Web Intern at the UNC General Alumni Association and the Digitization Intern at Campbell University.
  jpulliza:
      name: Jonathan Pulliza
      prof: false
      gravatar: 
      website: http://jpulliza.tumblr.com/
      github: jpulliza
      twitter: TriviaNerd86
      about:  MSIS student. Loves cooking, modular programming and LEGOs.
  kshaffer:
      name: Kyle Shaffer
      prof: false
      gravatar:
      website: 
      github: kylerthecreator
      twitter:
      about: First year MSIS student, novice Githubber, avid coffee drinker.  
  asherman:
      name: Amber Sherman
      prof: false
      gravatar:
      website:
      github: ans729
      twitter:
      about: Amber is a 2nd year MLS student hoping to find a big girl job with a digital library or archive.  
  atickner:
      name: Amanda Tickner
      prof: false
      gravatar:
      website: 
      github:
      twitter:
      about:  
  danielle:
      name: Danielle Wingler
      prof: false
      gravatar:
      website: 
      github: DanielleWingler
      twitter:
      about:  Danielle is a BSIS student. Looking forward to learning more about programming. Still exploring career paths within the information science field.
  zekuny:
      name: Zekun Yu
      prof: false
      gravatar: iyuzekun
      website: 
      github: zekuny
      twitter:
      about: Yu is a first year MSIS student. He likes programming and wants to learn more from class.
  josh:
    name: Josh Rice
    prof: false
    gravatar: 
    website: 
    github: joshrice
    twitter: biorice
    about: Josh is an MSIS student who plays on the UNC soccer team. 
=======
      prof: true
      gravatar: 0d0d432948d262195358f339768f1240
      website: http://www.elliotthauser.com
      github: eah13
      twitter: hauspoor
      about:  Elliott Hauser is a PhD Student in information science at UNC Chapel Hill.  He's hacking education as one of the cofounders of Trinket.io.  
  grant:
      name: Grant McLendon
      prof: true
      gravatar: eeb73c80c4450528bf5eac5f1dedae9e
      website: http://grantmclendon.com
      github: gerbal
      twitter: gerbal100
      about: Grant is a first year MSIS student. He's from Chapel Hil and like playing with new technologies and getting way in over his head.
  zbay:
      name: Zachary Williams
      prof: false
      gravatar: 
      website: http://zbay.github.io/spring2014/
      github: zbay
      twitter: 
      about:  Zach is a sophomore Information Science and Political Science double major at UNC. He hails from Fairfax, Virginia.
  Adrian:
      name: Adrian Ogletree
      prof: false
      gravatar: 46713fd106ce3203526cf52e9caa4c64
      github: aogletree
      twitter: oftheadriatic
      about: Adrian is a second year MSIS student. She is from Austin, Texas.
  katielmeyer:
      name: Katie Meyer
      prof: false
      gravatar: 1a03889fb33eb025aaf0f71fcde449ae
      website: http://www.katielmeyer.net
      github: katielmeyer
      twitter: katielmeyer
      about: Katie is a first year MSIS student from Raleigh NC. She's also a Web UI Developer at IBM.
  allen:
      name: Allen Lyons
      prof: false
      gravatar:
      website: http://www.unc.edu/~lyonsa/
      github: lyonsa
      twitter: lions8lyons
      about: Allen is a fourth year UNC undergraduate in the BSIS program. No idea what he is going to do after he graduates but hopefully he'll be doing something that makes money. Likes playing with new tech, watch tv and movies, reading comic books, playing video games, and spending time with his friends and family. Depending on the whole job thing he may also be consuming a considerable amount of alcohol this semester.
  bdferr:
      name: Brendan Ferreri-Hanberry
      prof: false
      gravatar:
      github: bdferr
      twitter:
      about: Brendan is an MSIS student from Virginia. In his free time, he writes articles about drug policy at ssdp.org/about/blog-contributors/brendan-ferreri-hanberry/ and at the-libertarian.co.uk, where he serves as an editor.
  tlchristian:
      name: Thu-Mai Christian
      prof: false
      github: tlchristian
      twitter: tl_christian
      about: Thu-Mai is a SILS PhD student and a data archivist at the Odum Institute. I will solve all of your data management problems.
  blucka12: 
      name: Oak Ritchie
      prof: false
      gravitar: 
      website: http://www.steadyflowblog.com
      github: blucka12
      twitter: oakritchie
      about: Oak is a first year MSIS student, and is learning.
  julie:
    name: Julie Seifert
    prof: false
    github: juliees39
    twitter: julieseifert
    about: Julie Seifert is a second year MSLS student. She is from Tampa, Florida and enjoys kayaking and other water sports.
  ethan:
      name: Ethan Kavanaugh
      prof: false 
      gravatar: 
      website: http://www.nooooooooooooooo.com/
      github: babykav
      twitter: ethankavanaugh
      about: Ethan is a senior BSIS student. Lover of bacon. Avid user of handrails. 
  dcowhig:
      name: David Cowhig
      prof: false
      gravatar: 
      website: http://www.unc.edu/~dcowhig
      github: dcowhig
      twitter:
      about: David is a student at the University of North Carolina. He is currently an Information Science (BSIS) major.
  haley:
      name: Haley Walton
      prof: false
      github: Gefionne
      twitter: hmwalts
      about: Haley is a second-year MSLS student. Librarian, equestrian, gamer.
  srmoore5:
    name: Sierra Moore
    prof: false
    website:
    github: srmoore5
    twitter:
    about: Sierra is a first year MSIS student
  agooch:
      name: Mandy Gooch
      prof: false
      gravatar:
      website: 
      github: agooch
      twitter: 
      about: Mandy is a second year MSLS student. She is from Virginia and has a background in Asian Studies. Currently she works as a Research Data Coordinator at The Odum Institute at UNC. 
  amanda:
      name: Amanda Holt
      prof:
      gravatar:
      website:
      github: holtam
      about: Amanda is a fourth year undergrad studying Information Science at UNC Chapel Hill.
  elizahinkes:
      name: Eliza Hinkes
      prof: false
      github: elizahinkes
      about: Eliza is a junior Information Science and History double major from Newton, NJ.
  laura:
      name: Laura Ashcraft
      prof: false
      gravatar:
      github: lasher09
      twitter: 
      about: Laura is a first year MLS student. She is from Long Beach, California. She likes learning new things.
  libbby:
      name: Libby Livingston
      prof: false
      gravatar:
      website:
      github: libbby
      twitter:
      about: Libby is a BSIS student in SILS. She double majors in Geography, and is working on a minor in Art History.
  xuxiang:
      name: Xuxiang Mao
      prof: false
      gravatar:
      github: maoxuxiang
      twitter:
      about: I am a first year MSIS student
  sunhwap:
      name: Sunhwa Park 
      prof: false
      gravatar:
      github: sunhwap
      twitter:
      about:
  brittany:
      name: Brittany Hayes
      prof: false
      gravatar:
      website:
      github: britth
      twitter:
      about: Brittany is a second year MSIS student. She is interested in information retrieval, data mining, and natural language processing.
  yonghao:
      name: Yonghao Yu
      prof: false
      gravator: 
      website:
      github: yonghaoy
      twitter: yonghao_yu
      about: yonghao is a second year graduate year of SILS student. He is from China.
  madeline:
      name: Madeline Coven
      prof: false
      gravatar:
      website:
      github: madeline13
      twitter:
      about: Madeline is a second-year MSIS student.  She enjoys data visualizations and information design.
  jacobthill:
      name: Jacob Hill
      prof: false
      gravatar:
      website:
      github: jacobthill
      twitter:
      about: Jacob is a second year PhD student. His research is in the area of digital humanities and Middle East studies.
  slaffer:
      name: Sophia Lafferty-Hess
      prof: false
      gravatar:
      website:
      github: slaffer
      twitter:
      about: Sophia is a third year dual-degree MSIS and Masters of Public Administration student.
  jtbeeker:
     name: Jeremy Beeker
     prof: false
     gravatar:
     website: http://www.unc.edu/~jtbeeker
     twitter:
     about: Jeremy is a junior undergraduate information science student at unc chapel hill. 
  jskaa:
     name: Jessica Feng
     prof: false
     gravatar:
     website:
     twitter:
     about: Jessica is a senior information science student at UNC.
  lei:
      name: Lei Wang
      prof: false
      gravator: 
      website:
      github: leiw414
      twitter: zuoyou414
      about: Lei Wang is a second year MSIS student. 
  chunxi:
      name: Chunxi Zhang
      prof: false
      gravator: 
      website:
      github: lanblue
      twitter: 
      about: Chunxi is a first year graduate year of SILS student. She is from China.
>>>>>>> b77e81d49f0bf0f945b5025ace5a79ac787b13b9
